### PR TITLE
Use yarn as node manager.

### PR DESCRIPTION
**Pull request by lisovskyvlad**
Yarn is just better, quicker and solid way to install all npm dependencies.

### CODE REVIEW

**Comment by davydovanton** [comment]
Hello, thanks for contribution.
I'm not sure that I want to use yarv now. That's why I'll merge this changes later.
Thanks again 👍

**Comment by davydovanton** [comment]
hey, could you rebase your branch? :)

**Comment by lisovskyvlad** [comment]
Done :)

**Comment by davydovanton** [comment]
thanks 👍

**Pull request merged**
