### PR TITLE
Use newrelic only in production

### PR DESCRIPTION
**Pull request by artofhuman**
I think we should use newrelic only in `production` mode, not in `development` and `test`.
@davydovanton WDYT?

### CODE REVIEW

**Comment by davydovanton** [comment]
Interesting proposal 👍 
But I think we can improve hanami newrelic gem instead this changes. WDYT?

**Comment by artofhuman** [comment]
No sure how, we should call `NewRelic::Agent.manual_start` in newrelic-hanami gem ?

**Comment by davydovanton** [comment]
no, I mean that we can check hanami env in `newrelic-hanami` instead of check in each hanami application.

**Comment by davydovanton** [comment]
okay, looks good for me 👍

**Pull request merged**
