### PR TITLE
Refactoring #85

### PR DESCRIPTION
**Pull request by davydovanton**
## What I did
1. Added new specs for issues without complexity labels
2. Used [dry-monads](http://dry-rb.org/gems/dry-monads/) instead tuples for better understanding and dropping all unnecessary conditions

Reference to https://github.com/ossboard-org/ossboard/pull/85

### CODE REVIEW

**Comment by googya** [comment]
nice job, one thing I concern is that is it worth including dry_monads for this just little refactoring? 

some times, I want to use dry_monads in project, but the other workmates think it not worthing including dry_monads.

**Comment by moofkit** [comment]
Nice! @davydovanton are you using dry monads in production?  What does your teammates think about it?

**Comment by davydovanton** [comment]
@moofkit I know some startups use dry-m in production. everyone is happy

**Comment by davydovanton** [comment]
@googya it was a just idea to use monads instead tuples (`[true, hash]`). I think in future we will have other cases for use dry-m.

I agree either monad can be difficult for some developers 😊

**Pull request merged**
